### ISSUE TITLE
dynamic obstacle recognition 

### ISSUE THREAD

**Issue by Eric666tht** [davutcanakbas/dynamic_object_removal#3]
Excuse me，what method is used to realize the dynamic obstacle recognition in this paper？

**Comment by davutcanakbas** [comment]
This is not a dynamic obstacle recognition package. The detection of dynamic objects is performed by Autoware's lidar_centerpoint package. Dynamic objects do not necessarily mean that they are currently in motion; rather, it means that they have the potential to move at any given time. For example, a car parked by the roadside is static, but since it may not always remain static and has the potential to move, it is considered a dynamic object.
